kind: pipeline
type: docker
name: default

trigger:
  branch:
    - dev

steps:
- name: build
  image: golang:1.20
  commands:
  - go mod download
  - go build -o modem-map ./cmd/main.go

- name: test
  image: golang:1.20
  commands:
  - go test -v ./...

- name: deploy-staging
  image: alpine
  commands:
    - apk add --no-cache rsync openssh
    - eval $(ssh-agent)
    - echo "$STAGING_SSH_KEY" | ssh-add -
    - rsync -avz --delete --progress -e "ssh -p 22 -o StrictHostKeyChecking=no" ./modem-map $STAGING_USER@$STAGING_HOST:/opt/modem-map/
    - rsync -avz --progress -e "ssh -p 22 -o StrictHostKeyChecking=no" ./internal/templates/ $STAGING_USER@$STAGING_HOST:/opt/modem-map/templates/
  environment:
    STAGING_USER:
      from_secret: staging_user
    STAGING_HOST:
      from_secret: staging_host
    STAGING_SSH_KEY:
      from_secret: staging_ssh_key

- name: restart-app
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: staging_host
    username:
      from_secret: staging_user
    password:
      from_secret: staging_password
    script:
      - systemctl restart modem-map
